In [1]:
!wget "https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv"

--2020-10-11 04:38:39--  https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.82.1, 2620:100:6032:1::a27d:5201
Connecting to www.dropbox.com (www.dropbox.com)|162.125.82.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/c6lmwqz67kpdsiq/review_dataset.csv [following]
--2020-10-11 04:38:39--  https://www.dropbox.com/s/raw/c6lmwqz67kpdsiq/review_dataset.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc9459eb634ce69e98120a667761.dl.dropboxusercontent.com/cd/0/inline/BBCudH_DuapUWAMTFWwS_GJtd3ggJABRmAZyfFQWGGtagzWGrJFGDh8-7hsz3RwvttegnPVmaT3dh2ZpBDaR8UMfv2q4x4AtfYZ3CuYCtMNj5nEz9F-9Ib17Gyhae28wHZg/file# [following]
--2020-10-11 04:38:40--  https://uc9459eb634ce69e98120a667761.dl.dropboxusercontent.com/cd/0/inline/BBCudH_DuapUWAMTFWwS_GJtd3ggJABRmAZyfFQWGGtagzWGrJFGDh8-7hsz3RwvttegnPVmaT3dh2ZpBDaR8UMfv2q4x

In [2]:
import pandas as pd
import numpy as np


In [3]:
df=pd.read_csv("review_dataset.csv")
df.head()

review label
0  The Buddy Holly Story opens on a shot of a yel...   pos
1  ***SPOILERS*** Like some evil Tinkers-to-Evers...   neg
2  Ghost of Dragstrip Hollow is a typical 1950's ...   neg
3  Whatever you do, don't stop watching when you ...   pos
4  This is one of those movies you think that the...   neg

In [4]:
df.shape

(20000, 2)

In [5]:
df['label'][0:10]

0    pos
1    neg
2    neg
3    pos
4    neg
5    neg
6    pos
7    neg
8    neg
9    pos
Name: label, dtype: object

In [6]:
df['review'][1]

'***SPOILERS*** Like some evil Tinkers-to-Evers-to-Chance double-play combination we have in "Omen IV" the evil seed of the deceased AntiChrist Damien Thorn come back. Terrorizing his parents his schoolmates his neighbors and finally the entire world as a she named Delia York, Asia Vieila. After being given to a "deserving" couple the Yorks Karen & Gene, Fay Grant & Michael Woods,by the Catholic Church\'s St. Francis orphanage.<br /><br />Little Delia didn\'t waste any time making her peasants felt by scratching her mom at a house party. Later Delia almost get killed by a runaway truck only to have herself saved by this "Devil Dog" named Ryder. Going to school Delia takes care of the local bully by getting the big guy to wet himself in front of all his classmates. Later when his father threatens the Yorks with a law suit she has his head sliced off in a self-induced traffic accident! Delia is someone that you never mess with if you know what\'s good for you.<br /><br />Meanwhile Dalia\

In [7]:
import re ##regular expression
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
sw=stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
print(sw)
len(sw)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

179

In [9]:
def clean_text(sample):
  sample=sample.lower()
  sample=sample.replace("<br /><br />", "")
  sample=re.sub("[^a-z]+"," ",sample)
  sample=sample.split(" ")
  sample=[word for word in sample if word not in sw]
  sample=" ".join(sample)
  return sample

In [10]:
clean_text(df['review'][1])

' spoilers like evil tinkers evers chance double play combination omen iv evil seed deceased antichrist damien thorn come back terrorizing parents schoolmates neighbors finally entire world named delia york asia vieila given deserving couple yorks karen gene fay grant michael woods catholic church st francis orphanage little delia waste time making peasants felt scratching mom house party later delia almost get killed runaway truck saved devil dog named ryder going school delia takes care local bully getting big guy wet front classmates later father threatens yorks law suit head sliced self induced traffic accident delia someone never mess know good meanwhile dalia dad gene becomes big man town thinks getting elected congress champion clean air green trees crowd instead letting smog concrete boys take neighborhood eye white house bratty strange daughter delia anything gene york sudden good fortune later jo ann hearen hired delia nanny truth comes strange evil powers jo new age type rea

In [11]:
df['review']=df['review'].apply(clean_text)

In [12]:
df['review']

0        buddy holly story opens shot yellow neon moon ...
1         spoilers like evil tinkers evers chance doubl...
2        ghost dragstrip hollow typical teens turmoil m...
3        whatever stop watching think movie hang around...
4        one movies think makers would refuse release t...
                               ...                        
19995    boy really bad saw videotape scenes soundtrack...
19996    larry fessenden thrashed comments forum well w...
19997    may may worst movie steve martin ever made cer...
19998    idea people thinking made film plot limited ac...
19999     groove tube initially shown video first video...
Name: review, Length: 20000, dtype: object

In [13]:
x=df['review'].values #input in ml
y=df['label'].values #output in ml

In [14]:
x_train=x[0:15000]
x_test=x[15000:20000]

y_train=y[0:15000]
y_test=y[15000:20000]

In [15]:
from sklearn.preprocessing import LabelEncoder #converting pos/neg to 1/0
le=LabelEncoder()
le.fit(y_train) #learning the mapping pos:1 neg:0

LabelEncoder()

In [16]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [17]:
y_train[0:20]

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0])

In [18]:
#bag of word model
#it converts sentences into numbers
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10000)
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=10000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [20]:
cv.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=10000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
x_train=cv.transform(x_train).toarray()

In [22]:
x_train.shape

(15000, 10000)

In [23]:
x_test=cv.transform(x_test).toarray()

In [24]:
x_test.shape

(5000, 10000)

#model training

In [25]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()

In [26]:
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [27]:
mnb.predict(x_test)

array([0, 0, 1, ..., 0, 0, 0])

In [28]:
mnb.score(x_test,y_test)

0.8416

#predict for one sentence

In [29]:
my_review="i was watching friends.. wonderfull, pleased to watch. comedy"

In [30]:
my_review=clean_text(my_review)
my_review

'watching friends wonderfull pleased watch comedy'

In [31]:
my_review=cv.transform([my_review])

In [32]:
mnb.predict(my_review)

array([1])

In [33]:
neg_review="i don't like this boring movie.., not full with comedy.no,no...no "
neg_review=clean_text(neg_review)
neg_review=cv.transform([neg_review])
mnb.predict(neg_review)

array([0])